//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usermanagementMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<right> rights { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<roles_modules_permissions> roles_modules_permissions { get; set; }
        public virtual DbSet<roles_modules_permissions_rights> roles_modules_permissions_rights { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_roles> users_roles { get; set; }
    }
}
