//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usermanagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_modules_permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public roles_modules_permissions()
        {
            this.roles_modules_permissions_rights = new HashSet<roles_modules_permissions_rights>();
        }
    
        public int id { get; set; }
        public int module_id { get; set; }
        public int role_id { get; set; }
        public bool is_default { get; set; }
    
        public virtual module module { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roles_modules_permissions_rights> roles_modules_permissions_rights { get; set; }
    }
}
