//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usermanagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_modules_permissions_rights
    {
        public int id { get; set; }
        public int roles_modules_permissions_id { get; set; }
        public int rights_id { get; set; }
        public bool is_default { get; set; }
    
        public virtual right right { get; set; }
        public virtual roles_modules_permissions roles_modules_permissions { get; set; }
    }
}
